<?php namespace ProcessWire;

class MarkupGoogleTranslate extends Process implements Module {

  public static function getModuleinfo() {
    return [
      'title' => 'Google Page Translate',
      'summary' => 'Provides a simple interface for site visitors to translate the current page to Google supported languages.',
      'author' => 'Jonathan Goodwin, warp-design.co.uk',
      'version' => 0.1,
    ];
  }

  //Utility to clean the URL to match the format Google Likes
  private function cleanUrl($url) {
    $cleanUrl = str_replace('-','--',$url);
    $cleanUrl = str_replace('.','-',$cleanUrl);
    return $cleanUrl;
  }

  private function buildGoogleTranslateUrl($languageIsoCode) {

    //Get current page URL
    $currentPagePath = wire('page')->url;

    /*
    - Clean the URL to match the format Google Likes
    - But ignore home page to avoid outputting an unnecessary extra '/' later on
    */
    if ($currentPagePath != '/') {
        $currentPagePath = $this->cleanUrl($currentPagePath);
    } else {
        $currentPagePath = '';
    }

    //Get host domain
    $host = $this->cleanUrl(wire('config')->httpHost);

    //Check if we're using http/https
    $rootUrl = wire('pages')->get('/')->httpUrl;
    $scheme = (strpos($rootUrl,'https') !== false) ? 'https' : 'http' ;

    //Combine to build the translate URL
    $translateUrl = 'https://'.$host.'.translate.goog/'.$currentPagePath.'?_x_tr_sch=http&_x_tr_sl=en&_x_tr_tl='.$languageIsoCode.'&_x_tr_hl=en&_x_tr_pto=wapp';

    return $translateUrl;

  }

  /*
  Known available language codes for translation based
  on https://cloud.google.com/translate/docs/languages
  */
  private function availableLanguages() {

    return array(
        "Afrikaans" => "af",
        "Albanian" => "sq",
        "Amharic" => "am",
        "Arabic" => "ar",
        "Armenian" => "hy",
        "Azerbaijani" => "az",
        "Basque" => "eu",
        "Belarusian" => "be",
        "Bengali" => "bn",
        "Bosnian" => "bs",
        "Bulgarian" => "bg",
        "Catalan" => "ca",
        "Cebuano" => "ceb",
        "Chinese (Simplified)" => "zh-CN",
        "Chinese (Traditional)" => "zh-TW",
        "Corsican" => "co",
        "Croatian" => "hr",
        "Czech" => "cs",
        "Danish" => "da",
        "Dutch" => "nl",
        "English" => "en",
        "Esperanto" => "eo",
        "Estonian" => "et",
        "Finnish" => "fi",
        "French" => "fr",
        "Frisian" => "fy",
        "Galician" => "gl",
        "Georgian" => "ka",
        "German" => "de",
        "Greek" => "el",
        "Gujarati" => "gu",
        "Haitian Creole" => "ht",
        "Hausa" => "ha",
        "Hawaiian" => "haw",
        "Hebrew" => "he",
        "Hindi" => "hi",
        "Hmong" => "hmn",
        "Hungarian" => "hu",
        "Icelandic" => "is",
        "Igbo" => "ig",
        "Indonesian" => "id",
        "Irish" => "ga",
        "Italian" => "it",
        "Japanese" => "ja",
        "Javanese" => "jv",
        "Kannada" => "kn",
        "Kazakh" => "kk",
        "Khmer" => "km",
        "Kinyarwanda" => "rw",
        "Korean" => "ko",
        "Kurdish" => "ku",
        "Kyrgyz" => "ky",
        "Lao" => "lo",
        "Latin" => "la",
        "Latvian" => "lv",
        "Lithuanian" => "lt",
        "Luxembourgish" => "lb",
        "Macedonian" => "mk",
        "Malagasy" => "mg",
        "Malay" => "ms",
        "Malayalam" => "ml",
        "Maltese" => "mt",
        "Maori" => "mi",
        "Marathi" => "mr",
        "Mongolian" => "mn",
        "Myanmar (Burmese)" => "my",
        "Nepali" => "ne",
        "Norwegian" => "no",
        "Nyanja (Chichewa)" => "ny",
        "Odia (Oriya)" => "or",
        "Pashto" => "ps",
        "Persian" => "fa",
        "Polish" => "pl",
        "Portuguese" => "pt",
        "Punjabi" => "pa",
        "Romanian" => "ro",
        "Russian" => "ru",
        "Samoan" => "sm",
        "Scots Gaelic" => "gd",
        "Serbian" => "sr",
        "Sesotho" => "st",
        "Shona" => "sn",
        "Sindhi" => "sd",
        "Sinhala (Sinhalese)" => "si",
        "Slovak" => "sk",
        "Slovenian" => "sl",
        "Somali" => "so",
        "Spanish" => "es",
        "Sundanese" => "su",
        "Swahili" => "sw",
        "Swedish" => "sv",
        "Tagalog (Filipino)" => "tl",
        "Tajik" => "tg",
        "Tamil" => "ta",
        "Tatar" => "tt",
        "Telugu" => "te",
        "Thai" => "th",
        "Turkish" => "tr",
        "Turkmen" => "tk",
        "Ukrainian" => "uk",
        "Urdu" => "ur",
        "Uyghur" => "ug",
        "Uzbek" => "uz",
        "Vietnamese" => "vi",
        "Welsh" => "cy",
        "Xhosa" => "xh",
        "Yiddish" => "yi",
        "Yoruba" => "yo",
        "Zulu" => "zu",
    );
  }

  public function displayTranslateWidget() {

    //Compile the available languages as select field options
    $options = '';
    foreach ($this->availableLanguages() as $title => $code) {
        $url = $this->buildGoogleTranslateUrl($code);
        $options .= '<option value="'.$url.'">'.$title.'</option>';
    }

    //Compile and output
    $out = '<select onchange="location = this.options[this.selectedIndex].value;">';
    $out .= '<option>Translate Page</option>';
    $out .= $options;
    $out .= '</select>';

    return $out;
  }

}